from _typeshed import Incomplete

class Benderscut:
    benders: Incomplete
    model: Incomplete
    name: Incomplete
    @classmethod
    def __init__(cls, *args, **kwargs) -> None:
        """Create and return a new object.  See help(type) for accurate signature."""
    def benderscutexec(self, *args, **kwargs): ...
    def benderscutexit(self, *args, **kwargs): ...
    def benderscutexitsol(self, *args, **kwargs): ...
    def benderscutfree(self, *args, **kwargs): ...
    def benderscutinit(self, *args, **kwargs): ...
    def benderscutinitsol(self, *args, **kwargs): ...
    def __reduce__(self): ...
    def __reduce_cython__(self, *args, **kwargs): ...
    def __setstate_cython__(self, *args, **kwargs): ...
