from pyscipopt import Constraint, Model
from pyscipopt.scip import Node

def getLocalConss(model: Model, node: Node | None = None) -> list[list[Constraint]]: ...
def getNLocalConss(model: Model, node: Node | None = None) -> list[int]: ...
